
variables:
  user: darrin
  hungry: meh



stages:
- stage: A
  jobs:
  - job: A1
  - job: A2
  steps:
  - bash: echo $USER

- stage: B
  jobs:
  - job: B1
    steps:
    - bash: echo "from B1 yall"
  - job: B2