
variables:
  user: darrin
  hungry: meh



stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'darrincecil (b491bf98-6ea2-4a07-a641-200d61d7a735)'
        appType: 'webAppLinux'
        WebAppName: 'darrincecilvroom'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
        RuntimeStack: 'DOTNETCORE|5.0'