
variables:
  user: darrin
  hungry: meh



stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: './new-web-api.csproj'
    - bash: ls 

- stage: B
  jobs:
  - job: B1
    steps:
    - bash: |
        echo 'this is only a test' > test.txt && ls /bin/Debug/net5.0/ref/
        cat test.txt
        pwd
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: test.txt
        artifactName: drop
  - job: B2
    dependsOn: B1
    steps:
    - bash: |
        echo 'printing directory....'
        ls
    # - task: DownloadBuildArtifacts@1
    #   inputs:
    #     buildType: 'current'
    #     downloadType: 'single'
    #     artifactName: 'drop'
    #     downloadPath: '$(System.ArtifactsDirectory)'