
variables:
  user: darrin
  hungry: meh



stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: './new-web-api.csproj'
    - bash: ls 
    - task: Docker@2
      inputs:
        containerRegistry: 'darrincecil-azurecr'
        repository: 'ado'
        command: 'buildAndPush'
        Dockerfile: './nginx/Dockerfile'

- stage: B
  jobs:
  - job: B1
    steps:
    - bash: |
        echo 'this is only a test' > test.txt
        cat test.txt
    - publish: test.txt
  - job: B2
    dependsOn: B1
    steps:
    - bash: |
        echo 'printing directory....'
        ls
    - download: current
      artifact: ./test.txt
      displayName: Just seeing if she works