
variables:
  user: darrin
  hungry: meh



stages:
- stage: A
  jobs:
  - job: A1
      steps:
      - bash: echo $USER
  - job: A2
    

- stage: B
  jobs:
  - job: B1
    steps:
    - bash: echo "from B1 yall"
  - job: B2