
variables:
  user: darrin
  hungry: meh



stages:
- stage: A
  jobs:
  - job: A1
   

- stage: B
  jobs:
  - job: B1
    steps:
    - bash: |
        echo 'this is only a test' > test.txt && ls
        cat test.txt
        pwd
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(System.ArtifactsDirectory)/test.txt
        artifactName: drop
  - job: B2
    steps:
    - bash: ls -a
    # - task: DownloadBuildArtifacts@1
    #   inputs:
    #     buildType: 'current'
    #     downloadType: 'single'
    #     artifactName: 'drop'
    #     downloadPath: '$(System.ArtifactsDirectory)'