# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  anotherVariable: 'wonk'
  one: initialValue
  two: blah
  group: test-variable-group
parameters:
- name: nickname
  type: string
  default: d-man

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
#Example of how to user parameters
# - bash: |
#     echo ${{ parameters.nickname }}

#Accessing the PAT if you need it
- bash: echo This script could use $SYSTEM_ACCESSTOKEN
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
- bash: |
    echo ${{ variables.one }}
    echo macro syntax $(one)
    echo '##vso[task.setvariable variable=two]secondValue2'
#this runtime change might need to be in a different bash step in order to work
- bash: | 
    echo the key is: $(storage-account-key)