
variables:
  user: darrin
  hungry: meh



stages:
- stage: A
  jobs:
  - job: A1
   

- stage: B
  jobs:
  - job: B1
    steps:
    - bash: |
        echo 'this is only a test' > test.txt
        cat test.txt
        pwd
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: drop
  - job: B2